### ISSUE TITLE
翻译官求latex源码

### ISSUE THREAD

**Issue by tiemuhua** [ZJU-FAST-Lab/ego-planner#12]
事情是这样的，我正在把这篇文章翻译成汉语，这样别人再去看这篇文章的时候就不用啃英文了。文本已经基本上翻译完了。能不能给我原文的latex代码，我实在不想打公式了，而且我没有插图。我的邮箱是tiemuhua@126.com。让我们携起手来，为中文机器人社区贡献自己的力量！

**Comment by USTfgaoaa** [comment]
@bigsuperZZZX Share the tex source it‘s OKay.
@tiemuhua 辛苦了

**Comment by bigsuperZZZX** [comment]
好嘞

**Comment by BlueeHole** [comment]
请问翻译的原文在哪呢

**Comment by BlueeHole** [comment]
请问翻译的结果在哪呢

**Comment by USTfgaoaa** [comment]
@tiemuhua How about translating the paper of ego-swarm as well : )
