### ISSUE TITLE
What is the drone tested in this paper?

### ISSUE THREAD

**Issue by loujiabin1994** [ZJU-FAST-Lab/ego-planner#19]
Is the firmware used PX4? And how about the aircraft hardware? Is it an all-in-one plane? thank you.

**Comment by bigsuperZZZX** [comment]
As mentioned in the paper page 6, column 1, "Real-world experiments are presented on the same flight platform of [19]...", where the hardware settings are released.
By the way, we use DJI N3 as the flight controller, and the plane is assembled by ourselves.
