### ISSUE TITLE
On which topic the Ego-planner publishes the optimal trajectory?

### ISSUE THREAD

**Issue by shubham-shahh** [ZJU-FAST-Lab/ego-planner#24]
On which topic the Ego-planner publishes the optimal trajectory? out of 

/ego_planner_node/a_star_list
/ego_planner_node/global_list
/ego_planner_node/goal_point
/ego_planner_node/goal_point_array
/ego_planner_node/init_list
/ego_planner_node/optimal_list
/ego_planner_node/optimal_list_array

/planning/bspline

**Comment by bigsuperZZZX** [comment]
/ego_planner_node/optimal_list for visualization
/planning/bspline for executing

**Comment by shubham-shahh** [comment]
> /ego_planner_node/optimal_list for visualization
> /planning/bspline for executing

Does Ego planner consider UAV dimensions for path planning?
