### ISSUE TITLE
The http of gitee is wrong,should be "https://gitee.com/iszhouxin/ego_planner", there is "ego-planner" in readme.

### ISSUE THREAD

**Issue by IngaVS** [ZJU-FAST-Lab/ego-planner#3]
![2020-09-08 10-32-23屏幕截图](https://user-images.githubusercontent.com/18420049/92427381-e79b0d00-f1be-11ea-8e2d-cf3cc69c924a.png)
![2020-09-08 10-31-06屏幕截图](https://user-images.githubusercontent.com/18420049/92427386-e964d080-f1be-11ea-9cee-e2e39ce50e8a.png)

**Comment by bigsuperZZZX** [comment]
Sorry for posting the wrong gitee URL and thanks for pointing out this mistake. I will correct it.
