### ISSUE TITLE
[ego_planner_node-1] 

### ISSUE THREAD

**Issue by MichaelLu-hku** [ZJU-FAST-Lab/ego-planner#30]
[ego_planner_node-1] process has died [pid 18372, exit code -11, cmd /home/minghao/catkin_ws/devel/lib/ego_planner/ego_planner_node /odom_world:=imu_odom /grid_map/odom:=imu_odom /grid_map/cloud:=/laser_cloud_surround /grid_map/pose:=/mavros/vision_pose/pose /grid_map/depth:=/camera/aligned_depth_to_color/image_raw __name:=ego_planner_node __log:=/home/minghao/.ros/log/b7e306d6-26af-11ec-b83e-200db04751e1/ego_planner_node-1.log].

I run ego planner with DJI-manifold 2-c, the node can be run at first, but after a few seconds this error occurs, how to fix it?
Than you for your help! ~~

**Comment by bigsuperZZZX** [comment]
The first thing to check is whether the drone flies out of the map that you allocated by parameters "map_size_x, map_size_y, map_size_z".
If the drone is inside the map region but this error still occurs, please use the ego-planner-swarm repo as recommended in the readme file of ego-planner.
This ego-planner repo is out of maintenance.
