### ISSUE TITLE
Some error appear, after setting'4.Use GPU or Not‘

### ISSUE THREAD

**Issue by WjMessi1** [ZJU-FAST-Lab/ego-planner#35]
After modifying according to '4.Use GPU or Not' in README.md, when I run  `roslaunch ego_planner simple_run.launch`
  the following error occured. Is there any solution?
```
max: 2.19722
thresh log: 1.38629
[ WARN] [1644378990.936752103]: WARNING: package://odom_visualization/meshes/hummingbird.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
[ WARN] [1644378990.937035293]: Can't assign material _missing_material_ to SubEntity of mesh_resource_marker_0 because this Material does not exist. Have you forgotten to define it in a .material script?
[ INFO] [1644378991.040601082]: threshold: 0.066521
[ INFO] [1644378991.161273645]: the number of points before optimization is 575999
[ INFO] [1644378991.164054434]: finish: infill 0.120000%
[ WARN] [1644378991.176236017]: Global Pointcloud received..
global map has points: 575999.
terminate called after throwing an instance of 'CudaException'
  what():  
[pcl_render_node-8] process has died [pid 32584, exit code -6, cmd /home/wjrobot/ego-planner/devel/lib/local_sensing_node/pcl_render_node ~global_map:=/map_generator/global_cloud ~odometry:=/visual_slam/odom __name:=pcl_render_node __log:=/home/wjrobot/.ros/log/ebe10b72-88bb-11ec-88e0-e0e1a9521b7c/pcl_render_node-8.log].
log file: /home/wjrobot/.ros/log/ebe10b72-88bb-11ec-88e0-e0e1a9521b7c/pcl_render_node-8*.log
[ WARN] [1644378991.585642287]: [Traj server]: ready.
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
[TRIG]: from INIT to GEN_NEW_TRAJ

```

**Comment by bigsuperZZZX** [comment]
All Cuda problems we encountered until now are all relevant to corrupted Cuda installation. 
Therefore we recommend you check your installation of Cuda or try the planner on another computer.
Hope this works.

**Comment by WjMessi1** [comment]
> All Cuda problems we encountered until now are all relevant to corrupted Cuda installation. Therefore we recommend you check your installation of Cuda or try the planner on another computer. Hope this works.

ok， thanks for your reply！ I am trying it on a new computer

**Comment by WjMessi1** [comment]
I have reinstalled my system. Configuration is ubuntu20.04, cuda11.6, now, the result of order `nvidia-smi` as follow:
![图片](https://user-images.githubusercontent.com/87363191/153811816-3e99f614-33ad-4756-9c42-eb920271b06d.png)
I can pass `catkin_make`, but still there are some warning：
![图片](https://user-images.githubusercontent.com/87363191/153813972-9895da75-2e5f-443b-ba07-868b0e812c68.png)
when I run `roslaunch ego_planner simple_run.launch`，no error occured, but some warning like this:
![图片](https://user-images.githubusercontent.com/87363191/153814821-926ff368-5df1-4d53-b454-a2b541eb1c6d.png)
I think it's related to the warning occur during `catkin_make`. Then the deep images are all black, the output of topic `/pcl_render_node/depth` are all 0.
![图片](https://user-images.githubusercontent.com/87363191/153814407-0e127827-9249-44b6-b074-69ed11f4729f.png)
Can this problem be solved?
One more question is how should I get the speed of the drone in the simulation? By which topic to echo? Thanks!!!

**Comment by bigsuperZZZX** [comment]
I also use Cuda 11 but no error occurs during compiling.
The warning during code running is relevant to rviz visualization and is nothing to do with Cuda, so you can just ignore it or convert the initial _.mesh_ file to a _.dae_ file to eliminate the warning.

Remember to config this:
![image](https://user-images.githubusercontent.com/26641182/153818596-e8c47b2e-82f2-4eec-9fbe-e8165f0ea1f4.png).
On my computer installed with Cuda 11 + 1660Ti, I set this to "-gencode arch=compute_75,code=sm_75" to enable depth rendering.

**Comment by bigsuperZZZX** [comment]
Sorry, I accidentally closed this issue. It has been reopened again.

**Comment by WjMessi1** [comment]
> Sorry, I accidentally closed this issue. It has been reopened again.

ok, thanks for your reply, I have tried your recommand method above, this still has no effect...... I think this warning has a great impact on planning. As you can see:
![7d1a10bf-663e-4cc9-9d7b-6ef96dcd1c48-9634069](https://user-images.githubusercontent.com/87363191/153890992-0b81d9ec-4138-44ef-abbe-deb8690efd0e.png)
The trajectory goes straight through the obstacle, almost in a straight line and no depth image output. I've had success with GPU before, but recently don't know what happened... I'm sorry, this question took your time. If it doesn't work, I will try to reinstall the system again. It may be the cause of cuda.
At last，how can I get the speed of the drone during operation in the simulation? By which rostopic？

**Comment by WjMessi1** [comment]
> Yes if there are no valid depth images, the planner has no obstacle information.
> 
> To get the drone speed, you just listen to the Odometry topic, which may be, reads like "/visual_slam/odom".

Hello! This problem is solved, it is really metaphysics. I reinstalled the system again, now the version of cuda is 11.2, and the nvidia-driver is 450, the previous problem may be the version of the kernel of the lunix system. Thank you！ I think you can close it this problem.

**Comment by WjMessi1** [comment]
How should I modify the detection range of the depth camera? The default detection range parameter seems to have no limit.

**Comment by bigsuperZZZX** [comment]
Our code doesn't provide this interface, but you can modify it just in the depth image callback function where you can check all the pixels and manually set the value which exceeds your threshold to zero.

**Comment by bigsuperZZZX** [comment]
If there are no more questions, I will close this issue.

**Comment by WjMessi1** [comment]
> 

ok， thank you！
