### ISSUE TITLE
How to change to other stereo camera

### ISSUE THREAD

**Issue by rsj007** [ZJU-FAST-Lab/ego-planner#36]
Hi, I want to change the d435i to a different stereo camera. How to modify the code?  Thanks a lot!!!

**Comment by bigsuperZZZX** [comment]
Changing a stereo camera doesn't need to modify the code.
You just check the topic connection using "rqt_graph" and modify the topic names of your added camera to make it compatible with the original topic names.
Note that the depth resolution of your camera has to be changed to 640*480.

**Comment by rsj007** [comment]
Thanks!
