### ISSUE TITLE
How can get global mockamap and first version mockamap? like gif:)

### ISSUE THREAD

**Issue by cygong** [ZJU-FAST-Lab/ego-planner#37]

**Comment by bigsuperZZZX** [comment]
Maybe I don't quite understand what you mean. Could you explain your question in more detail?

**Comment by cygong** [comment]
I see they offer good videos in “indoor.gif” and "outdoor.gif". 
Define the right picture in “indoor.gif”: global mockamap.
Define the centre picture in “indoor.gif”:  first version mockamap.
I want to kown, How can i with code or setting get them?
Thanks.

**Comment by bigsuperZZZX** [comment]
You can use tf messages to control the views in rviz. 
For more details, please refer to tf and rviz user guide.
