### ISSUE TITLE
Question about BsplineOptimizer

### ISSUE THREAD

**Issue by cygong** [ZJU-FAST-Lab/ego-planner#39]
i am trying to understanding your code.
i want to ask for Question about BsplineOptimizer.
In Function BsplineOptimizer::initControlPoints:  

1.what is different between "segment_ids", "bounds" and "final_segment_ids"?
2.How can from get {p and v} "a_star_pathes" and "segment_ids"? "intersection_point" ?

Thanks

**Comment by bigsuperZZZX** [comment]
同学建议你还是讲中文吧

**Comment by cygong** [comment]
我看论文里面提到的p and v 的计算非常少。我想问一下，具体在编程实践里面是怎么做的？
比如 在BsplineOptimizer::initControlPoints这个程序里面：
"segment_ids", "bounds" and "final_segment_ids" 这三个变量的不同是什么？
程序是怎么通过a_star_pathes 和Q进行匹配，然后生成 p和v 的？

谢谢。
