### ISSUE TITLE
Importing Real environment 

### ISSUE THREAD

**Issue by Amit10311** [ZJU-FAST-Lab/ego-planner#4]
Thank you for this great package for simulating MAV. I am running Ubuntu 16.04. The simulator is working perfectly. I want to set up my own environment. You have created the environment with the use of a `mockamap` package. I want to import the .dae environment structure.  Can you please guide me on how to set up the environment in your package.

I look forward to hearing from you. Thank you for your valuable time.

**Comment by bigsuperZZZX** [comment]
It's easy to do this. Use command `rqt_graph` to see the nodes and active topics
![image](https://user-images.githubusercontent.com/26641182/92547802-4f695a80-f288-11ea-9aa7-146fc9f64886.png)
The node _/mockamap_node_ at the left bottom of the figure is the node generating the map.
You can just to replace _/mockamap_node_ with your own map generating node publishing you map topic named _/map_generator/global_cloud_ of type _sensor_msgs/PointCloud2_ at a rate of every one or two seconds.

**Comment by Amit10311** [comment]
Thank you for your reply. I would like to mention that when  I am publishing the `pointclou2data` it's not visible in the `rviz.launch` but it's visible in the normal rviz.

**Comment by bigsuperZZZX** [comment]
Make sure that you have renamed your pointcloud topic to "/map_generator/global_cloud".
What's more, don't forget to disable the original _/mockamap_node_ .

**Comment by Amit10311** [comment]
In the map generating you are having these topics :
```
Node [/random_map_sensing]
Publications: 
 * /map_generator/global_cloud [sensor_msgs/PointCloud2]
 * /map_generator/local_cloud [sensor_msgs/PointCloud2]
 * /pcl_render_node/local_map [sensor_msgs/PointCloud2]

Subscriptions: 
 * /random_map_sensing/odometry [unknown type]
```
The point cloud data I am providing is prebuilt data. So, basically I am providing  `/map_generator/global_cloud [sensor_msgs/PointCloud2]`. While providing this data it shows:
[ WARN] [1600242929.182409695]: Global Pointcloud received.

Can you please guide me on how to set up the pre-built data in your package.

**Comment by bigsuperZZZX** [comment]
`[ WARN] [1600242929.182409695]: Global Pointcloud received.` means the global map has successfully received by the planner and everything work well. We use ROS_WARN(.) is just to let this message displayed in yellow, so that we can distinguish it from numerous message flow easier from termianl. 
You can publish the map only once, and be sure the planner has received the map when this "yellow message" is seen.
Our package has no built-in function for publishing pre-built data. However, any method that converts your .dae file to a ROS message is OK.

**Comment by Amit10311** [comment]
The cloud map is still not visible. My map is big, is there a limit of map dimension? 

I also like to know in which node the `click goals` are generated. I would like to choose the `click goal points` at high altitude. Could you please provide the information regarding it?

**Comment by bigsuperZZZX** [comment]
If there is no more questions, please close this issue, thanks.
