### ISSUE TITLE
The reason to suppress the slope of the collisioin cost

### ISSUE THREAD

**Issue by Joeyyuenjoyslife** [ZJU-FAST-Lab/ego-planner#40]
Hi, Here is Joey. I want to know is there any specific reason to suppress the slope of the collision cost item when distance is negative? i can't find further explanation in the paper, thanks a lot !
![image](https://user-images.githubusercontent.com/35419302/162641617-ffd0e53e-3e93-452f-9f30-77385ae09c84.png)

**Comment by bigsuperZZZX** [comment]
Well, it's a little bit complicated. We use a quasi-Newton method L-BFGS as our optimizer described in section "B. Numerical Optimization". It approximates the optimized function in a quadratic form. Therefore the more similar we formulate the cost function to a quadratic form, the faster convergence we can achieve in theory.

**Comment by Joeyyuenjoyslife** [comment]
> Thanks for your reply! it makes sense, I will close this issue.
