### ISSUE TITLE
Is the realsense driver of the project fit with Nvidia NX board?

### ISSUE THREAD

**Issue by JACKLiuDay** [ZJU-FAST-Lab/ego-planner#41]
Hi, guys. Thank you for your great work. I have some questions about the realsense driver which is used in the project. I want to apply it on the Nvidia NX board. Will this work? If I used the D435i outdoor with this driver, would it perform well?

**Comment by bigsuperZZZX** [comment]
I'm afraid it only works on x86 systems.

**Comment by JACKLiuDay** [comment]
> I'm afraid it only works on x86 systems.

Thank you for your reply.
