### ISSUE TITLE
a question in file "SO3Control.cpp"

### ISSUE THREAD

**Issue by 19ohh** [ZJU-FAST-Lab/ego-planner#42]
Hi, Gao, in **SO3Control.cpp** of the uav-simulator module in your Ego planner code, there are several parameters A, B, C, s (about in line 82-87), they are used to calculate the variable **force_** (_force_.noalias() = s * f + mass_ * g_ * Eigen::Vector3d(0, 0, 1);_) Can you please explain what is the theoretical basis for this calculation? Thank you!

**Comment by bigsuperZZZX** [comment]
It's just a geometry problem. The code changes the direction of the body-z vector to a limited angle to world-z. 
In fact, any reasonable engineering consideration works.
