### ISSUE TITLE
I can not get the gridmap

### ISSUE THREAD

**Issue by 001zwzwzw** [ZJU-FAST-Lab/ego-planner#44]
when i test the code with NX and D435i,but when i run the node ,i can not get the grid map.Then i look the rostopic echo grid_map/occupancy_inflate,but nothing in it.I want to know the reason that i get nothing.Do you meet the question?

![baffdab11193778b3a77fb6b5791fbf](https://user-images.githubusercontent.com/55043568/178539510-a2561785-57a2-47f4-a021-9e1412ca96e4.jpg)

**Comment by bigsuperZZZX** [comment]
I have no idea about this problem. Maybe you have to check the mapping code by yourselves.

**Comment by bigsuperZZZX** [comment]
If there are no more questions, I will close this issue.
