### ISSUE TITLE
Drone movement is too aggressive.

### ISSUE THREAD

**Issue by romaster93** [ZJU-FAST-Lab/ego-planner#47]
hello .

I am implementing drone avoidance using ego planner v2 and ardupilot and mavros controller.

Everything is excellent! I admire your research.

However, when the obstacle disappears from the drone's field of view, it changes the yaw direction of the drone too abruptly. Also, it twists too much on narrow roads.

Can I make a smoother path if I fix anything?

Please refer to my video.

https://youtu.be/mMYVuqe9s_o

https://youtu.be/c3ECgOdWexE

**Comment by Swadine** [comment]
Did you find a fix?

**Comment by bigsuperZZZX** [comment]
Please refer to:
https://github.com/ZJU-FAST-Lab/EGO-Planner-v2/issues/12
