### ISSUE TITLE
How to remove obstacles in the model

### ISSUE THREAD

**Issue by zrd1234** [ZJU-FAST-Lab/ego-planner#48]
Hello, how should I modify to remove the obstacles in the code? I want to observe the real world with my camera and display it in RVIZ. Thank you very much.

**Comment by bigsuperZZZX** [comment]
Just comment this block https://github.com/ZJU-FAST-Lab/ego-planner/blob/fcdfc5419dcc0c93105803e6f60b1b08b4e5152d/src/planner/plan_manage/launch/simulator.xml#L45

**Comment by zrd1234** [comment]
![c7e62b1d03b786f0868b37e50f5a99d](https://user-images.githubusercontent.com/96851901/187142590-05080f62-d49c-47ef-9587-76e6595fcd59.jpg)

Thanks for your reply, I have blocked all the codes here, and the operation effect is shown in the picture. The camera is D435i, and the algorithm is Vins-Mono. I want to get the real environment, and as my device moves, it also moves, please help me, thank you.

**Comment by zrd1234** [comment]
> Just comment this block
> 
> https://github.com/ZJU-FAST-Lab/ego-planner/blob/fcdfc5419dcc0c93105803e6f60b1b08b4e5152d/src/planner/plan_manage/launch/simulator.xml#L45

Hello, thank you for your reply. I have a new problem now.
After I passed in the topic of Vins-Mono, the picture was always on the right plane of the camera. May I ask how to solve this problem?
