### ISSUE TITLE
when install the Improved ROS-RealSense Driver :gpg: 从公钥服务器接收失败：No name

### ISSUE THREAD

**Issue by Bourne98** [ZJU-FAST-Lab/ego-planner#49]
![image](https://user-images.githubusercontent.com/68227952/188536413-17e51695-d3f2-4475-9545-72140504f7a6.png)

`(base) wangzichen@laptop:~$ sudo apt-key adv --keyserver keys.gnupg.net --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
[sudo] wangzichen 的密码： 
Executing: /tmp/apt-key-gpghome.AlSSTuGARp/gpg.1.sh --keyserver keys.gnupg.net --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
gpg: 从公钥服务器接收失败：No name
Executing: /tmp/apt-key-gpghome.utsfANDZnW/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
gpg: 密钥 C8B3A55A6F3EFCDE：“"CN = Intel(R) Intel(R) Realsense", O=Intel Corporation”未改变
gpg: 合计被处理的数量：1
gpg:              未改变：1
`

**Comment by bigsuperZZZX** [comment]
不要用了，这个两年多前的realsense版本已经被过时了
