### ISSUE TITLE
Min and Max was messed up?

### ISSUE THREAD

**Issue by Lr-2002** [ZJU-FAST-Lab/ego-planner#55]
https://sourcegraph.com/github.com/ZJU-FAST-Lab/ego-planner@c50669a58ae51e6e2a9c35dc614b153b9b4c8c75/-/blob/src/planner/plan_env/src/grid_map.cpp?L341:22&popover=pinned#tab=references
this is the problem source ,and the code is 
```cpp

double min_x = mp_.map_max_boundary_(0);
double min_y = mp_.map_max_boundary_(1);
double min_z = mp_.map_max_boundary_(2);
 
double max_x = mp_.map_min_boundary_(0);
double max_y = mp_.map_min_boundary_(1);
double max_z = mp_.map_min_boundary_(2);
```

Maybe the min and max was messed?

**Comment by bigsuperZZZX** [comment]
Not messed. Here is the initialization of min and max.
