### ISSUE TITLE
ego_planner是规划器还是规划器+执行器

### ISSUE THREAD

**Issue by 70loKirin** [ZJU-FAST-Lab/ego-planner#58]
最近刚接触ego，非常感谢你们能开源如此好的项目。
请问ego规划出的路径我应该如何让我的飞机比较准确的跟着规划路径走呢，ego有自带的接口吗（比如move_base会给出速度话题），或者有其他的什么方法吗
打扰了，非常感谢

**Comment by 2447643603jzp** [comment]
you can see  it from"https://github.com/ZJU-FAST-Lab/Fast-Drone-250",It is based on ego-planner

**Comment by 70loKirin** [comment]
> you can see it from"[https://github.com/ZJU-FAST-Lab/Fast-Drone-250",It](https://github.com/ZJU-FAST-Lab/Fast-Drone-250%22,It) is based on ego-planner

Thank you very much

**Comment by bigsuperZZZX** [comment]
确实
