### ISSUE TITLE
[ego_planner_node-1] process has died

### ISSUE THREAD

**Issue by lovZgump** [ZJU-FAST-Lab/ego-planner#6]
Thank you for this great work. I am running Ubuntu 16.04. But I can't  run the planner in simulation. When I launch the **run_in_sim.launch**, the process always died. I haven't change anything. Can you please guide me on how to fix the problem.

I am looking forward to hearing from you. Thank you for your valuable time.
![Screenshot from 2020-09-23 11-33-42](https://user-images.githubusercontent.com/26085004/93964389-0938ee80-fd92-11ea-855f-ecf2a8dc0f62.png)

**Comment by bigsuperZZZX** [comment]
We encountered a similar problem(not exactly the same) and it was proved to be a BUG. This occurs on a computer with limited computing resources. We fixed this bug but has not been committed. So we commit it. We added the following code in _ego_planner_fsm.cpp_, so you can manually modify the code as the following picture or re-download the repository. Hoping this will solve you problem.
![zxzx](https://user-images.githubusercontent.com/26641182/94014141-b84ee780-fddd-11ea-83ca-f29be32c1db6.png)

**Comment by lovZgump** [comment]
Thank you for your reply. The problem has been fixed. Thanks again.
