### ISSUE TITLE
ZED instead of D435i

### ISSUE THREAD

**Issue by EhrazImam** [ZJU-FAST-Lab/ego-planner#64]
Hi @bigsuperZZZX  Hope you are doing well I want to use ZED camera instead of d435, As i am able to run it with D435 i want know what parameters i need to change apart from depth topic and intrinsic values.
Do i need to change something over here
https://github.com/ZJU-FAST-Lab/ego-planner/blob/fcdfc5419dcc0c93105803e6f60b1b08b4e5152d/src/planner/plan_manage/launch/advanced_param.xml#L87-L94

**Comment by bigsuperZZZX** [comment]
Make sure the resolution is 640*480. No more modifications are required.

**Comment by EhrazImam** [comment]
I am using 720*480
so do i need to change something or i have to make it 640*480

**Comment by bigsuperZZZX** [comment]
Correcting [this line](https://github.com/ZJU-FAST-Lab/ego-planner/blob/fcdfc5419dcc0c93105803e6f60b1b08b4e5152d/src/planner/plan_env/src/grid_map.cpp#L89) should be OK

**Comment by FPSychotic** [comment]
If I'm using 320x240 should I change that line too?

**Comment by bigsuperZZZX** [comment]
I think so.

**Comment by DIY-create** [comment]
> Hi @bigsuperZZZX Hope you are doing well I want to use ZED camera instead of d435, As i am able to run it with D435 i want know what parameters i need to change apart from depth topic and intrinsic values. Do i need to change something over here
> 
> https://github.com/ZJU-FAST-Lab/ego-planner/blob/fcdfc5419dcc0c93105803e6f60b1b08b4e5152d/src/planner/plan_manage/launch/advanced_param.xml#L87-L94

May I ask if your experiment was successful?

I also used a ZED2i camera to replace the realsense d435i.

 I replaced the topic of the depth image, changed the intrinsics of the depth image, and in the "ego planner/src/planner/plan_ Env/src/grid_ The map. cpp "code has modified the resolution to suit the resolution, and I have ensured that the depth image is normal.

But after I opened rviz, it still didn't display any maps. Do you know what other steps I need to take?

 Thank you very much
