### ISSUE TITLE
Trajectory tracking control

### ISSUE THREAD

**Issue by zrd1234** [ZJU-FAST-Lab/ego-planner#65]
Hello, I subscribe /planning/pos_cmd to send to my robot, but I find some deviation from the trajectory of the planning department. Is there any good trajectory following strategy to solve it.

**Comment by bigsuperZZZX** [comment]
It depends on the real robot you use. We use this high-level controller for precise trajectory tracking.

**Comment by bigsuperZZZX** [comment]
This controller [https://github.com/ZJU-FAST-Lab/Fast-Drone-250/tree/master/src/realflight_modules/px4ctrl](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/tree/master/src/realflight_modules/px4ctrl)

**Comment by zrd1234** [comment]
> It depends on the real robot you use. We use this high-level controller for precise trajectory tracking.

Hello, I did not use UAV. In the simulation, PID was used for its trajectory tracking, but I did not find it. Would you please tell me where it is?

**Comment by bigsuperZZZX** [comment]
Which simulation you refer to？
