### ISSUE TITLE
替换环境地图

### ISSUE THREAD

**Issue by selfInnovator** [ZJU-FAST-Lab/ego-planner#67]
能否加载pcd文件生成点云地图来构建地图环境，我直接在random_forest_sensing.cpp中加载pcd点云替代随机生成地图函数，结果地图构建失败

**Comment by bigsuperZZZX** [comment]
理论上是没问题的，我用过读取现有pcd地图。
你可以看下pcl库怎么保存和读取现有文件，可能是版本不一致，pcl库对版本还挺敏感的。

**Comment by Sunnybigboy** [comment]
你

> 能否加载pcd文件生成点云地图来构建地图环境，我直接在random_forest_sensing.cpp中加载pcd点云替代随机生成地图函数，结果地图构建失败
【你好 请问如何让替换环境中的地图 我想把障碍物的形状改为立方体的形式 】
