### ISSUE TITLE
运行自动起飞命令后WIFI经常自动断开

### ISSUE THREAD

**Issue by jieren30** [ZJU-FAST-Lab/ego-planner#69]
机载电脑使用的是intel 的NUC，连接的实验室WiFi网络，运行自动起飞命令后远程桌面经常断开连接，用外接屏幕查看是因为WiFi断开连接，并且无法重连。请问需要为机群单独配置一个WiFi吗？

**Comment by bigsuperZZZX** [comment]
可以试试买个USB的WiFi网卡
