### ISSUE TITLE
some questions about function initControlPoints in file bspline_optimizer.cpp

### ISSUE THREAD

**Issue by tiemuhua** [ZJU-FAST-Lab/ego-planner#7]
![image](https://user-images.githubusercontent.com/46767782/94011541-1aa5e900-fdda-11ea-88b6-95a7907c7b16.png)
MINIMUM_PERCENT is 0.0, so minimum_points should be 0, so the bool expression in line 413 should always be false, what is the purpose of these codes?

**Comment by bigsuperZZZX** [comment]
In some situations in the early time, we find that one single control point is unable to produce enough repulsive force. One effective way is to put some force onto adjacent points to make the trajectory producing stronger force.
The parameter MINIMUM_PERCENT specified how much control points will be assigned force for one obstacle. But we set this to 0, which still works OK...

**Comment by tiemuhua** [comment]
> In some situations in the early time, we find that one single control point is unable to produce enough repulsive force. One effective way is to put some force onto adjacent points to make the trajectory producing stronger force.
> The parameter MINIMUM_PERCENT specified how much control points will be assigned force for one obstacle. But we set this to 0, which still works OK...

so do you means that line 413 to line 422 can be removed?

**Comment by bigsuperZZZX** [comment]
It depends on the environment you want to fly in. If the environment contains many big obstacles, we recommend you to keep this code and set the MINIMUM_PERCENT to 10.0 ~ 20.0 if the planner performs unsatisfactory. Or this code can be removed.

**Comment by bigsuperZZZX** [comment]
If there is no more questions, please close this issue, thanks.
