### ISSUE TITLE
How to add waypoints in the planning?

### ISSUE THREAD

**Issue by HZhang1003** [ZJU-FAST-Lab/ego-planner#70]
very nice work! Thank you for your contributions to open source. Ego-planner has excellent planning performance.
I wonder if it is possible to add additional waypoints constraints to the planning, which could allow the UAV to pass through the set positions? If so, how should I achieve it?
Looking for your reply and thanks a lot.

**Comment by bigsuperZZZX** [comment]
I think this answer can solve your problem:
https://github.com/ZJU-FAST-Lab/ego-planner/issues/66#issuecomment-1471869062

**Comment by HZhang1003** [comment]
Thank you. I get it.
