### ISSUE TITLE
ego_planner error

### ISSUE THREAD

**Issue by Bruce-Si** [ZJU-FAST-Lab/ego-planner#73]
I got the following error when using ego_planner almost every time. Very occasionally it works well. 
![ego_planner_node error](https://user-images.githubusercontent.com/55371740/226227043-095d3ef4-a0ee-48ad-97d0-5dacf69b7d83.png)
The environment is unbuntu18.04 + melodic, I reinstalled the system and environment many times, it didn't work. Can anyone help me? 
By the way, the log file doesn't exit...

**Comment by Swadine** [comment]
What is your map size?

**Comment by Bruce-Si** [comment]
> What is your map size?

map_size_x = 100, map_size_y = 100, map_size_z = 5

**Comment by bigsuperZZZX** [comment]
print out the odometry position to see if it goes divergence.

**Comment by Bruce-Si** [comment]
@bigsuperZZZX The following is the odometry position, it seems ok since the map_size_x=100, map_size_y=100, map_size_z=5
![ego_planner_odometry](https://user-images.githubusercontent.com/55371740/227877330-3d53ceb0-25fd-4f1c-813b-ceb13cca45a4.png)

**Comment by bigsuperZZZX** [comment]
I have no idea about that. Never encounter such an error.

**Comment by Swadine** [comment]
@Bruce-Si 
I have encountered this issue, somehow reducing the map size fixed it, but its not a feasible solution but then you'll have to shift to a better machine.

**Comment by Bruce-Si** [comment]
Thank you. I tried to reduce the map size but it still did't work.😥Maybe I should try a different machine...

**Comment by bigsuperZZZX** [comment]
You could try our recent stable version [https://github.com/ZJU-FAST-Lab/EGO-Planner-v2](https://github.com/ZJU-FAST-Lab/EGO-Planner-v2).

**Comment by Bruce-Si** [comment]
> You could try our recent stable version https://github.com/ZJU-FAST-Lab/EGO-Planner-v2.

Thank you for your great work, I'll have a try.
