### ISSUE TITLE
Occupancy Grid Publish Rate

### ISSUE THREAD

**Issue by Kaapeine** [ZJU-FAST-Lab/ego-planner#75]
Hello, I'm experiencing a weird issue. The occupancy grid publish rate keeps varying, depending on the point cloud input. If the point cloud comes from a 640x480 image, the grid map is published at 1.5 Hz. But if we switch to 480x270, then we get a 20 Hz Grid Map. Any idea why it would behave like this? The grid map publishing looks to be independent of the depth input, so why is the rate varying so much?

**Comment by bigsuperZZZX** [comment]
Please evaluate the computer performance.

**Comment by Kaapeine** [comment]
Yes, that was the bottleneck, thank you!
