### ISSUE TITLE
vscode IntelliSense对于eigen的支持问题

### ISSUE THREAD

**Issue by Safpped** [ZJU-FAST-Lab/ego-planner#78]
作者您好：
       请问您是否在Xavier NX上的vs code中打开过ego-planner项目文件夹，我在Xavier可以正常编译项目，但是在vscode中打开时显示找不到eigen中的MatrixXd和VectorXd等第三方变量，P.S. 已按照教程中进行编译，生成了compile_command.json
![屏幕截图(18)](https://user-images.githubusercontent.com/76218329/232043311-fb05db2b-5568-4743-a349-64e47a2bba7b.png)

**Comment by Safpped** [comment]
此问题已解决，bug原因为vscode针对arm的开发适配问题，微软开发人员提供解决方案如下：
![5080f63da643364b7f94c8af02a5e72](https://user-images.githubusercontent.com/76218329/232201174-0d4e6b96-464c-40f5-99e5-56da996c3eba.png)
更方便的解决方案为在.vscode文件夹下创建一个eigen_fix.h，内容如下图
![image](https://user-images.githubusercontent.com/76218329/232201294-0c26501f-9b31-4278-9d7a-f54c5f9733e5.png)
然后在c_cpp_properties.json中，在forcedInclude路径中添加eigen_fix.h的路径".vscode/eigen_fix.h"
![image](https://user-images.githubusercontent.com/76218329/232201756-fa3f4bb3-15b5-44f3-b990-93deb40f9d83.png)
但是由于本项目在c_cpp_properties.json中使用了compileCommands配置选项，会导致vscode强制按cmake产生的编译指令进行头文件搜索，会忽略forceinclude路径，解决方案为注释compileCommands配置选项
![image](https://user-images.githubusercontent.com/76218329/232201815-195ac141-bd41-4ea4-a05e-69de50f27843.png)
在c_cpp_properties.json中手动添加includepath
![image](https://user-images.githubusercontent.com/76218329/232201830-91be247d-6ad0-4261-8031-cd3d70832fb8.png)

**Comment by bigsuperZZZX** [comment]
Mark⭐
