### ISSUE TITLE
可能的注释错误

### ISSUE THREAD

**Issue by Safpped** [ZJU-FAST-Lab/ego-planner#79]
![image](https://user-images.githubusercontent.com/76218329/232201089-24c5d582-371a-40a1-ae66-ab29c3c465a7.png)
您好:
      在uniform_bspline.h文件中第20行可能出现了注释错误，是否N*3 Matrix应该为3 * N Matrix？

**Comment by bigsuperZZZX** [comment]
是的，所有3维向量默认列向量

**Comment by Safpped** [comment]
您好，我想问一下，为什么在swarm- formation项目中提到的两篇论文没有采用ego-planner的front end搜索一条初始路径呢？

**Comment by bigsuperZZZX** [comment]
ego-planner的前端局部性比较强，适合单机，但不适合集群协同分配

**Comment by Safpped** [comment]
谢谢，解答了我的疑惑
