### ISSUE TITLE
使用安装最新Jetpack的Nvidia开发板安装过程中报错

### ISSUE THREAD

**Issue by Safpped** [ZJU-FAST-Lab/ego-planner#81]
英伟达最新Jetpack5.0.2自带opencv 4.5.4，可能会在编译完成后的链接步骤中出现ld链接器报错，有可能是新版本一些差异性所导致。
解决方法为修改src/planner/plan_envwen文件夹下的CMakeLists，在target_link_libraries中加入${OpenCV_LIBS}

**Comment by bigsuperZZZX** [comment]
多谢
