### ISSUE TITLE
请问，如何将vins定位变为动捕定位

### ISSUE THREAD

**Issue by 1094780291** [ZJU-FAST-Lab/ego-planner#90]
你好，我想在室内想尝试用动捕替换vins进行定位，但是看完代码对具体改哪块的内容还是无从下手，所以想麻烦问一下用动捕来定位怎么进行修改呢，麻烦您了

**Comment by zzy5323** [comment]
你可以把config文件的odom输入话题改为你自己的odom话题 [https://github.com/ZJU-FAST-Lab/ego-planner/blob/master/src/planner/plan_manage/launch/run_in_sim.launch](url)的第八行

**Comment by zzy5323** [comment]
你可以把config文件的odom输入话题改为你自己的odom话题 [的第八行](你可以把config文件的odom输入话题改为你自己的odom话题 https://github.com/ZJU-FAST-Lab/ego-planner/blob/master/src/planner/plan_manage/launch/run_in_sim.launch

**Comment by zzy5323** [comment]
你可以把config文件的odom输入话题改为你自己的odom话题[这边](https://github.com/ZJU-FAST-Lab/ego-planner/blob/master/src/planner/plan_manage/launch/run_in_sim.launch)的第八行
